### ISSUE TITLE
SlimuxREPLSendSelection does not execute selection on target pane

### ISSUE THREAD

**Issue by krzkrzkrz** [epeli/slimux#28]
SlimuxREPLSendSelection sends the selection to target pane but doesnt execute it. Kind of weird.

On the other hand, SlimuxREPLSendLine sends to target pane and executes...

Is this the expected behaviour?

**Comment by slashfoo** [comment]
@dvbuntu extend your selection to include the end of the line (using '$' when there is another line after the selection), the command in intended to send only the selection and not add to it; and the corner case is when there is no newline that can be sent when extending the selection to the end of line.
