### ISSUE TITLE
Slimux ignores a pane if vim is run outside tmux

### ISSUE THREAD

**Issue by apirogov** [epeli/slimux#50]
I run vim outside tmux and my REPL inside. In this setup something went broken lately - Slimux "eats" one pane, when I have one pane open it says there are none, if there are multiple, it seems to ignore the first.

When I set
let g:slimux_exclude_vim_pane = 0

it works correctly again, so it seems that this filtering breaks down somehow if vim itself is not inside tmux, I guess. It should not be necessary to set this option if vim is not even inside tmux.

**Comment by slashfoo** [comment]
That is correct, I'll work on fixing this bug. Thanks for opening the report.

**Comment by slashfoo** [comment]
```
        let l:current_pane_id = system('tmux display-message -p "#{session_name}:#{window_index}.#{pane_index}"')
```

This line returns "session:" (blank for window and pane) which would make slimux ignore all panes. I'm going to patch this in a bit.

**Comment by slashfoo** [comment]
The bug isn't related to that line, but it's an example of cases I had not thought of when I patched in the feature.

**Comment by slashfoo** [comment]
@apirogov I didn't know the commit would close the ticket immediately, please reopen it if the issue persists. I tested the options a bit, it should basically ignore the exclusion flags if vim is not running from within tmux.

**Comment by apirogov** [comment]
Ok, thanks! Just tried it, seems to work fine now.
