### ISSUE TITLE
Slimux not Affecting the Selected Tmux Pane

### ISSUE THREAD

**Issue by publicus** [epeli/slimux#56]
Hello,

I just found out about Slimux (having previously been using vim-slime), and am excited to try it out! However, I haven't been able to get Slimux working, and so am wondering whether I'm doing something wrong, or if there might be a compatibility bug with my version of Tmux and/or Vim.

# Versions:

* `tmux -V` tells me that I'm using version 1.9a
* `vim --version` tells me that I'm using version "7.4 (2013 Aug 10)"

* I'm using the master branch of Slimux, at the current commit (as of this writing), f8ae770. I installed it using Pathogen. I know that the install worked, because Vim recognizes the Slimux commands and doesn't give any error messages when I try to use them.

# Replicating the Issue:

Here are the steps I'm taking when trying to use Slimux:

1. Start a tmux session with `tmux new-session -s "Test"`
1. Split the tmux window with `Ctrl+b %`
1. In one pane of the split tmux window, launch R (or python)
1. In the other pane, launch vim
1. In vim:
	1. Write `5+5`
	1. Navigate the cursor to be on the same line as the `5+5`
	1. In normal mode, do `:SlimuxREPLSendLine`
		1. Slimux now prompts me to select a tmux window.
			* I can navigate up and down. However, when I press the spacebar, nothing happens (no overlay of which window is which)
			* Using the Slimux selection window, I select the tmux pane that's running R or python, and press Enter.
			* Vim's status bar says ":SlimuxREPLSendLine" (i.e., it was recognized as a command, with no errors), but **nothing happens in the other tmux pane.**

* Nothing happens in the other tmux pane when I use `SlimuxShellRun`, either (e.g., with just bash running in the other tmux pane, using `:SlimuxShellRun ls *\**` in vim).
* `SlimuxSendKeysPrompt` and `SlimuxSendKeysLast` **do** work, however.

Am I forgetting to set something up here? From the Readme and blog posts I've read, I'm unsure whether there's more setup I should be doing.

**Comment by slashfoo** [comment]
hey, I'm not able to replicate the bug, what OS are you using? and can you send the output of `vim --version`?

I have not tested the `spacebar` for selecting, but I will check that one, using enter, however, should have selected the window, and sent the line successfully. I wouldn't expect it to be broken because of anything in the "vim --version" ouptut specially because you're running the same version of vim that I am.

I'll come up with a minimal vimrc so we can debug what's up and rule out that it may be vim/tmux.

**Comment by gsunjka** [comment]
Hello, same here. Everythin worked fine until 30 minutes ago when I updated my plugins. Now nothing happens. I use vim-plug for plugin management, tmux 1.8 and vim 7.4.

**Comment by gsunjka** [comment]
I went back to 2f0030a6f5f25af295088f2d3ebf353d08ade438 and now everything works as expected again. Excellent plugin, by the way.

**Comment by slashfoo** [comment]
Ah, that explains it, named buffers are mentioned in the changes from tmux 1.9a to 2.0.

@epeli should we roll back this commit for now to support older versions of tmux and try to fix the issue #51 (cc: @sunaku ) in another way? If we don't we should at least document the point where compatibility breaks. Thanks @gsunjka for the help and finding the breaking commit.

**Comment by sunaku** [comment]
@gsunjka When you said "I went back to 2f0030a and now everything works as expected again", did you really mean that commit or the one immediately preceding it (0ff0e9b49faef3a72e29c352fde81f26484d8406)? :confused:

I ask because 2f0030a and master are currently the _same_ (with respect to their git tree contents). :christmas_tree:

**Comment by publicus** [comment]
Sorry, I've been away; thank you for your attention to this! To confirm, @slashfoo, I'm on openSUSE 13.1. Here's the full output of `vim --version`:

```
VIM - Vi IMproved 7.4 (2013 Aug 10)
Included patches: 1-52
Compiled by 'http://www.opensuse.org/'
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      +X11
-dnd             +modify_fname    +signs           +xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/current"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -I/usr/local/include  -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=1 -funwind-tables -fasynchronous-unwind-tables -g -Wall -pipe -fno-strict-aliasing      
Linking: gcc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.18.1/x86_64-linux-thread-multi/CORE   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lSM -lICE  -lm -lnsl    -ltinfo -lacl -lattr -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.18.1/x86_64-linux-thread-multi/CORE  -L/usr/local/lib64 -fstack-protector  -L/usr/lib/perl5/5.18.1/x86_64-linux-thread-multi/CORE -lperl -lm -ldl -lcrypt -lpthread 
```

Other plugins I currently have installed: `nerdtree`, `snipmate`, `table-mode`, and `tagbar`.

**Comment by publicus** [comment]
Also, I just confirmed, following @sunaku, that doing `git checkout 0ff0e9b` causes Slimux to work for me, as well (Doing a checkout on 2f0030a does **not** work). Cheers! :smiley:

**Comment by gsunjka** [comment]
@sunaku Sorry, I ment 0ff0e9b.

**Comment by sunaku** [comment]
Thanks all :+1:, PR #57 submitted to fix this issue. :cake:

**Comment by publicus** [comment]
Thank you!

**Comment by slashfoo** [comment]
Merged the request, @publicus and @gsunjka can you please confirm the fix? And again, thanks @sunaku.

**Comment by gsunjka** [comment]
Works here. Thanks a lot to all, especially @sunaku. :+1:

**Comment by publicus** [comment]
Works for me, as well. Thank you all!
