### ISSUE TITLE
vim hanging when using SlimuxREPLSendLine

### ISSUE THREAD

**Issue by arifb** [epeli/slimux#61]
Hello,
Great plugin, invaluable to me. Having issues however, may have been on upgrade to iTerm2 3.0, not sure. 

When I issue a SlimuxREPLSendLine, MacVim is unresponsive, with the cursor remaining in the vim command line (bottom). 

Looking at running processes, seems to be `tmux load-buffer -b Slimux -` the command that is causing the hanging. Killing that allows me to continue using vim. 

Obviously I'm not able to send text out to the REPL however.

**Comment by sunaku** [comment]
Are you using tmux 2.2?  See https://github.com/tmux/tmux/pull/416 and try this workaround https://github.com/tmux/tmux/pull/416#issuecomment-223184163. :neckbeard:

**Comment by arifb** [comment]
@sunaku Appreciate the tip - I am using tmux 2.2. Setting that environment variable doesn't do the trick however. I will try to pull in your patch and recompile tmux later today.

**Comment by arifb** [comment]
Rebuilt tmux including https://github.com/tmux/tmux/pull/416 and the issue persists. If there is more debugging that would be helpful to provide, please let me know.

**Comment by sunaku** [comment]
Oops, I missed the fact that you're on a Mac. :sweat_smile: The workaround and patch you tried only apply to Linux.  Report this issue upstream at tmux: it might be a Mac-related issue that they (have yet to?) know about.

**Comment by gzagatti** [comment]
Hi @arifb did you managed to find a way around the problem. I'm having exactly the same issue after updating tmux and trying to `export EVENT_NOEPOLL=1` as suggested in the link above. Did you have any luck in fixing the issue? I'm also using OS X.

**Comment by arifb** [comment]
@gzagatti I downgraded to tmux 2.1 for now

**Comment by gzagatti** [comment]
Yes @arifb I did the same and it works.

**Comment by sunaku** [comment]
Okay, I've got it! :neckbeard: MacOSX users, please try these settings with tmux 2.2:

```
export EVENT_NOKQUEUE=1
export EVENT_NOPOLL=1
```

These magic environment variables come from tmux's MacOSX-specific `osdep_event_init()` function, whose source code is available at <https://github.com/tmux/tmux/blob/2.2/osdep-darwin.c#L77-L78>.

Note: This is the same approach I followed for solving this issue for tmux 2.2 running under Linux. :penguin:

**Comment by gzagatti** [comment]
Thanks @sunaku it works like a charm

**Comment by slashfoo** [comment]
@arifb can you confirm that it works? I also just pushed a change that lets you specify the path to your tmux, this should allow for better flexibility.

I had an issue with the same symptoms when the tmux session was running one version and slimux found a tmux of another version, hopefully either the mention above or the configuration will alleviate the problem.

**Comment by hlegius** [comment]
@slashfoo not sure if for @arifb worked, but I tried in tmux 2.2 and worked like a boss! 👍 
Without those envs, vim crashes like described above.

**Comment by slashfoo** [comment]
thanks @hlegius I'll close this issue then.
