### ISSUE TITLE
Slimux breaks when `g:slimux_tmux_path` is unset

### ISSUE THREAD

**Issue by mganjoo** [epeli/slimux#65]
See https://github.com/epeli/slimux/commit/55a01a2f87dbec6db18f5199cdf5493aba5dca59#commitcomment-19102917 for details. An extraneous newline causes commands to be split up as follows:

```
/usr/bin/tmux
 -V
```
instead of
```
/usr/bin/tmux -V
```
and the former causes shell errors.

**Comment by mganjoo** [comment]
I'd be happy to file a PR later if you prefer.

**Comment by slashfoo** [comment]
@mganjoo thanks for the report, system() call to find vim has a newline, I'm stripping it in the commit above. Can you verify that it solves the issue on your end so we can close?

**Comment by mganjoo** [comment]
Seems to be working now; thanks!
