### ISSUE TITLE
SlimuxSendKeys() bug?

### ISSUE THREAD

**Issue by slagtermaarten** [epeli/slimux#72]
I'm experiencing a problem, could this be a bug or am I doing something wrong? I'm using Vim 8.0.55 in tmux 2.3, Mac OS Sierra. Thank you!

`:SlimuxSendKeys 'anything' <CR>`
OR
`:SlimuxSendKeys "traceback()" <CR>`

```
Error detected while processing function SlimuxSendKeys[4]..<SNR>92_Send:
line   31:
E115: Missing quote: ' send-keys -t " . target . " " . keys)
E116: Invalid arguments for function system
```

**Comment by slagtermaarten** [comment]
Reading the code `:SlimuxSendCode()` provides the functionality I was looking for

**Comment by habibalamin** [comment]
Can we reopen this? I'm experiencing the same issue, and `SlimuxSendCode` is unsuitable for my purposes.

I've tested on Homebrew's MacVim (8.1) as well as the system Vim (8.0). Neither work. I'm on High Sierra 10.13.6.

**Comment by HwanGoh** [comment]
Fixed the issue by going to line 228 of slimux.vim and replacing:
call system(g:slimux_tmux_path . ' send-keys -t " . target . " " . keys)

with:
call system(g:slimux_tmux_path . " send-keys -t " . target . " " . keys)
